import React from "react";

import Head from "next/head";

import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";

import Header from "../components/Header";

import { ThemeContextProvider } from "../components/Theme";

import "../styles/index.css";

function MyApp({ Component, pageProps }) {
  return (
    <ThemeContextProvider>
      <Head>
        <title>Алгоритмические основы мультимедийных технологий</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="static/favicon.ico" />
      </Head>
      <Header />
      <Container maxWidth="1800px">
        <Component {...pageProps} />
      </Container>
      <Typography variant="caption" display="block" className="caption">
        © 2021 All rights reserved.
      </Typography>
    </ThemeContextProvider>
  );
}

export default MyApp;
